CREATE TABLE ST_CANDIDATO 
(
  MATRICULA NVARCHAR2(20) NOT NULL 
, NOMBRE NVARCHAR2(30) NOT NULL 
, APELLIDOP NVARCHAR2(30) NOT NULL 
, APELLIDOM NVARCHAR2(30) 
, CORREO NVARCHAR2(30) NOT NULL 
, TELEFON NVARCHAR2(12) NOT NULL 
, CARRERA NVARCHAR2(30) NOT NULL 
, GENERACION NVARCHAR2(30) 
, TEMATESIS NVARCHAR2(50) NOT NULL 
, DIRECTORTESIS NVARCHAR2(30) NOT NULL 
, TRABAJA NVARCHAR2(20) NOT NULL 
, LUGARTRABAJO NVARCHAR2(40) 
, HORARIOTRABAJO NVARCHAR2(20)
, ACEPTADO NVARCHAR2(10)
, IMAGEN BLOB 
, CONSTRAINT ST_CANDIDATO_PK PRIMARY KEY (MATRICULA)ENABLE 
);

drop table ST_CANDIDATO;

INSERT INTO "SYSTEM"."ST_CANDIDATO" (MATRICULA, NOMBRE, APELLIDOP, APELLIDOM, CORREO, TELEFON, CARRERA, GENERACION, TEMATESIS, DIRECTORTESIS, TRABAJA, IMAGEN) VALUES ('13-003-0485', 'yonathan', 'Martinez', 'Barradas', 'j-ma@hotmail.es', '5528154692', 'Ing. Software', '13', 'Todavia no se', 'Calle 11 mz h lote 24', 'no', empty_blob())


UPDATE ST_CANDIDATO SET ACEPTADO = 'no'
WHERE MATRICULA = '15-003-0548';
