CREATE TABLE ST_CANDIDATO 
(
  MATRICULA NVARCHAR2(20) NOT NULL 
, NOMBRE NVARCHAR2(30) NOT NULL 
, APELLIDOP NVARCHAR2(30) NOT NULL 
, APELLIDOM NVARCHAR2(30) 
, CORREO NVARCHAR2(30) NOT NULL 
, TELEFON NVARCHAR2(12) NOT NULL 
, CARRERA NVARCHAR2(30) NOT NULL 
, GENERACION NVARCHAR2(30) 
, TEMATESIS NVARCHAR2(50) NOT NULL 
, DIRECTORTESIS NVARCHAR2(30) NOT NULL 
, TRABAJA NVARCHAR2(20) NOT NULL 
, LUGARTRABAJO NVARCHAR2(40) 
, HORARIOTRABAJO NVARCHAR2(20)
, ACEPTADO NVARCHAR2(10)
, IMAGEN BLOB 
, CONSTRAINT ST_CANDIDATO_PK PRIMARY KEY (MATRICULA)ENABLE 
);

CREATE TABLE ST_ASESOR 
(
  ID_ASESOR NUMBER NOT NULL 
, NOMBRE NVARCHAR2(40) NOT NULL 
, CUBICULO NVARCHAR2(40) NOT NULL 
, CORREO NVARCHAR2(40) NOT NULL 
, H_ASESORIOA NVARCHAR2(40) NOT NULL 
, ASIGNADO NVARCHAR2(2) NOT NULL 
, CONSTRAINT ST_ASESOR_PK PRIMARY KEY (ID_ASESOR)ENABLE 
);

CREATE TABLE ST_GRUPO 
(
  ID_GRUPO NUMBER NOT NULL
, ID_ASESOR NUMBER NOT NULL
, CONSTRAINT ST_GRUPO_PK PRIMARY KEY (ID_GRUPO)ENABLE 
, CONSTRAINT ST_GRUPO_ASESOR_FK FOREIGN KEY (ID_ASESOR)
  REFERENCES ST_ASESOR (ID_ASESOR)
);


CREATE TABLE ST_MI_GRUPO 
(
  ID_GRUPO NUMBER NOT NULL
, MATRICULA NVARCHAR2(20) NOT NULL
, CONSTRAINT ST_MI_GRUPO_GRUPO_FK FOREIGN KEY (ID_GRUPO)
    REFERENCES ST_GRUPO (ID_GRUPO)
, CONSTRAINT ST_MI_GRUPO_CANDIDATO_FK FOREIGN KEY (MATRICULA)
    REFERENCES ST_CANDIDATO (MATRICULA)
);







drop table ST_ASESOR;

INSERT INTO "SYSTEM"."ST_CANDIDATO" (MATRICULA, NOMBRE, APELLIDOP, APELLIDOM, CORREO, TELEFON, CARRERA, GENERACION, TEMATESIS, DIRECTORTESIS, TRABAJA, IMAGEN) VALUES ('13-003-0485', 'yonathan', 'Martinez', 'Barradas', 'j-ma@hotmail.es', '5528154692', 'Ing. Software', '13', 'Todavia no se', 'Calle 11 mz h lote 24', 'no', empty_blob());
INSERT INTO "SYSTEM"."ST_ASESOR" (ID_ASESOR, NOMBRE, CUBICULO, CORREO, H_ASESORIOA, ASIGNADO) VALUES ('1', 'Juan Carlos', 'D-302', 'juan@hotmail.es', 'Diario 3 a5pm', 'no');
INSERT INTO "SYSTEM"."ST_MI_GRUPO" (ID_GRUPO, MATRICULA) VALUES ('1', '15-003-0548')


UPDATE ST_CANDIDATO SET ACEPTADO = 'no'
WHERE MATRICULA = '15-003-0548';


SELECT COUNT(*) AS NUMASE FROM ST_ASESOR;

SELECT COUNT(*) AS NUMASE FROM ST_MI_GRUPO
WHERE ID_GRUPO = 1;

SELECT COUNT(*) AS NUMASE FROM ST_GRUPO;


SELECT * FROM ST_CANDIDATO;



SELECT C.MATRICULA, C.NOMBRE,C.APELLIDOP, M.ID_GRUPO, A.NOMBRE FROM ST_CANDIDATO C INNER JOIN ST_MI_GRUPO M 
              ON(C.MATRICULA = M.MATRICULA) INNER JOIN ST_GRUPO G
              ON(M.ID_GRUPO = G.ID_GRUPO) INNER JOIN ST_ASESOR A
              ON(G.ID_ASESOR = A.ID_ASESOR);
              
SELECT E.NOMBRE, COUNT(*) AS ENTREGADOS FROM EXAM_EMPLEADO E FULL OUTER JOIN EXAM_PAQUETE_PROG_ENTREGA Pe
  ON(E.ID_EMPLEADO = Pe.ID_EMPLEADO) FULL OUTER JOIN EXAM_PAQUETE P
  ON(Pe.ID_PAQUETE = P.ID_PAQUETE) LEFT JOIN EXAM_ESTADO_PAQUETE Ep
  ON(P.ID_EDO_PAQUETE = Ep.ID_EDO_PAQUETE)
  WHERE E.ID__PUESTO = 1111
  AND Ep.ID_ESTADO = 3
  GROUP BY E.NOMBRE
  ORDER BY ENTREGADOS ASC;   
  
  SELECT C.MATRICULA, C.NOMBRE, C.APELLIDOP, M.ID_GRUPO, A.NOMBRE 
  FROM ST_CANDIDATO C INNER JOIN ST_MI_GRUPO M ON(C.MATRICULA = M.MATRICULA) 
  INNER JOIN ST_GRUPO G ON(M.ID_GRUPO = G.ID_GRUPO)
  INNER JOIN ST_ASESOR A ON(G.ID_ASESOR = A.ID_ASESOR);

